/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as PhotoshopRouteImport } from './routes/photoshop'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhotoshopFeedRouteImport } from './routes/photoshop_.feed'

const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoshopRoute = PhotoshopRouteImport.update({
  id: '/photoshop',
  path: '/photoshop',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoshopFeedRoute = PhotoshopFeedRouteImport.update({
  id: '/photoshop_/feed',
  path: '/photoshop/feed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/feed': typeof FeedRoute
  '/photoshop': typeof PhotoshopRoute
  '/tools': typeof ToolsRoute
  '/trends': typeof TrendsRoute
  '/photoshop/feed': typeof PhotoshopFeedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/feed': typeof FeedRoute
  '/photoshop': typeof PhotoshopRoute
  '/tools': typeof ToolsRoute
  '/trends': typeof TrendsRoute
  '/photoshop/feed': typeof PhotoshopFeedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/feed': typeof FeedRoute
  '/photoshop': typeof PhotoshopRoute
  '/tools': typeof ToolsRoute
  '/trends': typeof TrendsRoute
  '/photoshop_/feed': typeof PhotoshopFeedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/feed'
    | '/photoshop'
    | '/tools'
    | '/trends'
    | '/photoshop/feed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/feed'
    | '/photoshop'
    | '/tools'
    | '/trends'
    | '/photoshop/feed'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/feed'
    | '/photoshop'
    | '/tools'
    | '/trends'
    | '/photoshop_/feed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  FeedRoute: typeof FeedRoute
  PhotoshopRoute: typeof PhotoshopRoute
  ToolsRoute: typeof ToolsRoute
  TrendsRoute: typeof TrendsRoute
  PhotoshopFeedRoute: typeof PhotoshopFeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photoshop': {
      id: '/photoshop'
      path: '/photoshop'
      fullPath: '/photoshop'
      preLoaderRoute: typeof PhotoshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photoshop_/feed': {
      id: '/photoshop_/feed'
      path: '/photoshop/feed'
      fullPath: '/photoshop/feed'
      preLoaderRoute: typeof PhotoshopFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  FeedRoute: FeedRoute,
  PhotoshopRoute: PhotoshopRoute,
  ToolsRoute: ToolsRoute,
  TrendsRoute: TrendsRoute,
  PhotoshopFeedRoute: PhotoshopFeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
