/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoCreateRouteImport } from './routes/video-create'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PhotoshopRouteImport } from './routes/photoshop'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CategoryRouteImport } from './routes/category'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhotoshopFeedRouteImport } from './routes/photoshop_.feed'

const VideoCreateRoute = VideoCreateRouteImport.update({
  id: '/video-create',
  path: '/video-create',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoshopRoute = PhotoshopRouteImport.update({
  id: '/photoshop',
  path: '/photoshop',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoshopFeedRoute = PhotoshopFeedRouteImport.update({
  id: '/photoshop_/feed',
  path: '/photoshop/feed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/category': typeof CategoryRoute
  '/create': typeof CreateRoute
  '/feed': typeof FeedRoute
  '/photoshop': typeof PhotoshopRoute
  '/pricing': typeof PricingRoute
  '/tools': typeof ToolsRoute
  '/trends': typeof TrendsRoute
  '/video-create': typeof VideoCreateRoute
  '/photoshop/feed': typeof PhotoshopFeedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/category': typeof CategoryRoute
  '/create': typeof CreateRoute
  '/feed': typeof FeedRoute
  '/photoshop': typeof PhotoshopRoute
  '/pricing': typeof PricingRoute
  '/tools': typeof ToolsRoute
  '/trends': typeof TrendsRoute
  '/video-create': typeof VideoCreateRoute
  '/photoshop/feed': typeof PhotoshopFeedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/category': typeof CategoryRoute
  '/create': typeof CreateRoute
  '/feed': typeof FeedRoute
  '/photoshop': typeof PhotoshopRoute
  '/pricing': typeof PricingRoute
  '/tools': typeof ToolsRoute
  '/trends': typeof TrendsRoute
  '/video-create': typeof VideoCreateRoute
  '/photoshop_/feed': typeof PhotoshopFeedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/category'
    | '/create'
    | '/feed'
    | '/photoshop'
    | '/pricing'
    | '/tools'
    | '/trends'
    | '/video-create'
    | '/photoshop/feed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/category'
    | '/create'
    | '/feed'
    | '/photoshop'
    | '/pricing'
    | '/tools'
    | '/trends'
    | '/video-create'
    | '/photoshop/feed'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/category'
    | '/create'
    | '/feed'
    | '/photoshop'
    | '/pricing'
    | '/tools'
    | '/trends'
    | '/video-create'
    | '/photoshop_/feed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CategoryRoute: typeof CategoryRoute
  CreateRoute: typeof CreateRoute
  FeedRoute: typeof FeedRoute
  PhotoshopRoute: typeof PhotoshopRoute
  PricingRoute: typeof PricingRoute
  ToolsRoute: typeof ToolsRoute
  TrendsRoute: typeof TrendsRoute
  VideoCreateRoute: typeof VideoCreateRoute
  PhotoshopFeedRoute: typeof PhotoshopFeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-create': {
      id: '/video-create'
      path: '/video-create'
      fullPath: '/video-create'
      preLoaderRoute: typeof VideoCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photoshop': {
      id: '/photoshop'
      path: '/photoshop'
      fullPath: '/photoshop'
      preLoaderRoute: typeof PhotoshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category': {
      id: '/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photoshop_/feed': {
      id: '/photoshop_/feed'
      path: '/photoshop/feed'
      fullPath: '/photoshop/feed'
      preLoaderRoute: typeof PhotoshopFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CategoryRoute: CategoryRoute,
  CreateRoute: CreateRoute,
  FeedRoute: FeedRoute,
  PhotoshopRoute: PhotoshopRoute,
  PricingRoute: PricingRoute,
  ToolsRoute: ToolsRoute,
  TrendsRoute: TrendsRoute,
  VideoCreateRoute: VideoCreateRoute,
  PhotoshopFeedRoute: PhotoshopFeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
